#!/usr/bin/env python3
# Generated by Open AI's Chat GPT 5.2

import argparse, re
import numpy as np

Q20 = 2**20

def load_q20_csvish(path):
    rows = []
    with open(path, "r", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # supports comma-separated or whitespace-separated
            parts = [p.strip() for p in line.split(",")] if "," in line else re.split(r"\s+", line)
            try:
                rows.append([float(x) for x in parts])
            except ValueError:
                continue
    a = np.asarray(rows, dtype=float)
    if a.ndim != 2 or a.shape[1] < 4:
        raise ValueError(f"{path}: expected >=4 numeric columns, got shape {a.shape}")
    return a[:, :4] / Q20  # counts

def detrend_linear(x):
    n = x.size
    t = np.arange(n, dtype=float)
    A = np.vstack([t, np.ones(n)]).T
    m, b = np.linalg.lstsq(A, x, rcond=None)[0]
    return x - (m*t + b)

def welch_psd(x, fs, nperseg=1024):
    # Minimal Welch (no scipy dependency). Hanning window.
    x = np.asarray(x, float)
    n = x.size
    nperseg = min(nperseg, n)
    if nperseg < 16:
        raise ValueError("Not enough samples for PSD.")
    step = nperseg // 2
    w = np.hanning(nperseg)
    w_norm = np.sum(w**2)

    psd_accum = None
    k = 0
    for start in range(0, n - nperseg + 1, step):
        seg = x[start:start+nperseg] * w
        X = np.fft.rfft(seg)
        P = (np.abs(X)**2) / (fs * w_norm)
        psd_accum = P if psd_accum is None else psd_accum + P
        k += 1

    psd = psd_accum / max(k, 1)
    freqs = np.fft.rfftfreq(nperseg, d=1.0/fs)
    return freqs, psd

def pooled_sigma(a, b):
    return np.sqrt(0.5*(np.var(a, ddof=1) + np.var(b, ddof=1)))

def avg_by_tau(x, fs, tau_s):
    # average into non-overlapping blocks of length tau_s
    m = int(round(tau_s * fs))
    if m < 1:
        raise ValueError("tau too small for given fs.")
    n = (x.size // m) * m
    if n < m:
        raise ValueError("Not enough samples for the requested tau.")
    return x[:n].reshape(-1, m).mean(axis=1)

def analyze_pair(south, north, fs, trim_frac, tau_list, bw_hz):
    # trim edges to avoid transitions
    def trim(x):
        n = x.size
        k = int(round(trim_frac * n))
        return x[k:n-k] if (2*k < n) else x

    out = {}
    for idx, name in [(0,"raw"), (1,"spatial"), (2,"temporal"), (3,"combined")]:
        s = trim(south[:, idx])
        n = trim(north[:, idx])

        # steady-state means
        mu_s, mu_n = float(np.mean(s)), float(np.mean(n))
        delta = mu_n - mu_s

        # detrended residual noise (time domain)
        rs = detrend_linear(s)
        rn = detrend_linear(n)
        sig = pooled_sigma(rs, rn)

        snr = abs(delta)/sig
        snr_db = 20*np.log10(snr)

        # PSD / noise density (use concatenated residuals to stabilize estimate)
        r = np.concatenate([rs, rn])
        freqs, psd = welch_psd(r, fs=fs, nperseg=min(1024, r.size))

        # integrate noise 0..bw_hz
        bw = min(bw_hz, freqs[-1])
        mask = (freqs > 0) & (freqs <= bw)
        # approximate integral via trapezoid
        noise_rms_bw = np.sqrt(np.trapz(psd[mask], freqs[mask])) if np.any(mask) else float("nan")
        snr_bw_db = 20*np.log10(abs(delta)/noise_rms_bw) if noise_rms_bw > 0 else float("nan")

        # SNR vs averaging time (tau)
        tau_results = []
        for tau_s in tau_list:
            s_tau = avg_by_tau(s, fs, tau_s)
            n_tau = avg_by_tau(n, fs, tau_s)
            delta_tau = float(np.mean(n_tau) - np.mean(s_tau))
            rs_tau = detrend_linear(s_tau)
            rn_tau = detrend_linear(n_tau)
            sig_tau = pooled_sigma(rs_tau, rn_tau)
            snr_tau_db = 20*np.log10(abs(delta_tau)/sig_tau)
            tau_results.append((tau_s, delta_tau, sig_tau, snr_tau_db))

        out[name] = {
            "delta": delta,
            "mu_s": mu_s,
            "mu_n": mu_n,
            "sigma_detrended": sig,
            "snr_db_detrended": float(snr_db),
            "noise_rms_0_bw": float(noise_rms_bw),
            "snr_db_0_bw": float(snr_bw_db),
            "tau_curve": tau_results,
        }
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--south", required=True)
    ap.add_argument("--north", required=True)
    ap.add_argument("--fs", type=float, default=60.0, help="sample rate of log lines (Hz)")
    ap.add_argument("--trim", type=float, default=0.10, help="fraction trimmed from each end")
    ap.add_argument("--bw", type=float, default=10.0, help="bandwidth for integrated-noise SNR (Hz)")
    ap.add_argument("--tau", type=float, nargs="*", default=[1.0], help="averaging times to report (s)")
    args = ap.parse_args()

    south = load_q20_csvish(args.south)
    north = load_q20_csvish(args.north)

    res = analyze_pair(south, north, fs=args.fs, trim_frac=args.trim, tau_list=args.tau, bw_hz=args.bw)

    print(f"Settings: fs={args.fs:.3f} Hz, trim={args.trim:.2f}, BW={args.bw:.2f} Hz, tau={args.tau}")
    for name, r in res.items():
        print(f"\n[{name}]")
        print(f"  Δ (mean north - mean south): {r['delta']:.6f} counts")
        print(f"  σ (detrended pooled RMS):    {r['sigma_detrended']:.6f} counts RMS")
        print(f"  SNR (detrended):             {r['snr_db_detrended']:.2f} dB")
        print(f"  noise RMS 0..BW:             {r['noise_rms_0_bw']:.6f} counts RMS")
        print(f"  SNR in 0..BW:                {r['snr_db_0_bw']:.2f} dB")
        print("  SNR vs averaging time:")
        for tau_s, d, sig, snr_db in r["tau_curve"]:
            print(f"    tau={tau_s:>6.3f}s: Δ={d:>10.6f}, σ={sig:>10.6f}, SNR={snr_db:>7.2f} dB")

if __name__ == "__main__":
    main()
